# Generated by Django 5.1.3 on 2024-11-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_formapagamento_alter_pedido_options_pedido_atendente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedido'},
        ),
    ]
