# Generated by Django 4.1.4 on 2024-11-12 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '1 - Base',
                'verbose_name_plural': '1 - Base',
            },
        ),
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Embalagem',
                'verbose_name_plural': 'Adm - Embalagem',
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('vaiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Entregador',
                'verbose_name_plural': 'Adm - Entregador',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Formas de Pagamento',
                'verbose_name_plural': 'Adm - Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Sabor',
                'verbose_name_plural': 'Adm - Sabor',
            },
        ),
        migrations.CreateModel(
            name='TipoMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Tipo de Mercadoria',
                'verbose_name_plural': 'Adm - Tipo de Mercadoria',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Adm - Unidade de Medida',
                'verbose_name_plural': 'Adm - Unidade de Medida',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='media')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.base')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.sabor')),
            ],
            options={
                'verbose_name': '2 - Produto',
                'verbose_name_plural': '2 - Produto',
                'unique_together': {('base', 'sabor', 'preco')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('pago', models.BooleanField(default=False)),
                ('entregue', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.entregador')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.formapagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3 - Pedido',
                'verbose_name_plural': '3 - Pedido',
            },
        ),
        migrations.CreateModel(
            name='ItensCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='base.produto')),
            ],
        ),
        migrations.AddField(
            model_name='base',
            name='embalagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.embalagem'),
        ),
        migrations.AddField(
            model_name='base',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tipomercadoria'),
        ),
        migrations.AddField(
            model_name='base',
            name='um',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.unidademedida'),
        ),
        migrations.AlterUniqueTogether(
            name='base',
            unique_together={('tipo', 'um', 'embalagem')},
        ),
    ]
