# Generated by Django 4.1.4 on 2024-11-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='atendente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregador',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='produto',
            name='base',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sabor',
        ),
        migrations.AlterField(
            model_name='entregador',
            name='nome',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Embalagem',
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
        migrations.DeleteModel(
            name='ItensCarrinho',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Sabor',
        ),
        migrations.DeleteModel(
            name='TipoMercadoria',
        ),
        migrations.DeleteModel(
            name='UnidadeMedida',
        ),
    ]
