# Generated by Django 4.1.4 on 2024-11-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Embalagem',
                'verbose_name_plural': 'Adm - Embalagem',
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Sabor',
                'verbose_name_plural': 'Adm - Sabor',
            },
        ),
        migrations.CreateModel(
            name='TipoMercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Tipo de Mercadoria',
                'verbose_name_plural': 'Adm - Tipo de Mercadoria',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Adm - Unidade de Medida',
                'verbose_name_plural': 'Adm - Unidade de Medida',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('embalagem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.embalagem')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.tipomercadoria')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.unidademedida')),
            ],
            options={
                'verbose_name': '1 - Base',
                'verbose_name_plural': '1 - Base',
                'unique_together': {('tipo', 'um', 'embalagem')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='media')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.base')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.sabor')),
            ],
            options={
                'verbose_name': '2 - Produto',
                'verbose_name_plural': '2 - Produto',
                'unique_together': {('base', 'sabor', 'preco')},
            },
        ),
    ]
